import pandas as pd
data = pd.read_csv(r'./train.csv')

def normalize(data):
    data[['JOINT_HEAD_X','JOINT_NECK_X','JOINT_LEFT_SHOULDER_X',
        'JOINT_RIGHT_SHOULDER_X','JOINT_LEFT_ELBOW_X','JOINT_RIGHT_ELBOW_X',
        'JOINT_LEFT_HAND_X','JOINT_RIGHT_HAND_X','JOINT_TORSO_X',
        'JOINT_LEFT_HIP_X','JOINT_RIGHT_HIP_X','JOINT_LEFT_KNEE_X',
        'JOINT_RIGHT_KNEE_X','JOINT_LEFT_FOOT_X','JOINT_RIGHT_FOOT_X']] = \
        data[['JOINT_HEAD_X','JOINT_NECK_X','JOINT_LEFT_SHOULDER_X',
        'JOINT_RIGHT_SHOULDER_X','JOINT_LEFT_ELBOW_X','JOINT_RIGHT_ELBOW_X',
        'JOINT_LEFT_HAND_X','JOINT_RIGHT_HAND_X','JOINT_TORSO_X',
        'JOINT_LEFT_HIP_X','JOINT_RIGHT_HIP_X','JOINT_LEFT_KNEE_X',
        'JOINT_RIGHT_KNEE_X','JOINT_LEFT_FOOT_X','JOINT_RIGHT_FOOT_X']].sub(data['JOINT_TORSO_X'], axis=0)

    data[['JOINT_HEAD_Y','JOINT_NECK_Y','JOINT_LEFT_SHOULDER_Y',
        'JOINT_RIGHT_SHOULDER_Y','JOINT_LEFT_ELBOW_Y','JOINT_RIGHT_ELBOW_Y',
        'JOINT_LEFT_HAND_Y','JOINT_RIGHT_HAND_Y','JOINT_TORSO_Y',
        'JOINT_LEFT_HIP_Y','JOINT_RIGHT_HIP_Y','JOINT_LEFT_KNEE_Y',
        'JOINT_RIGHT_KNEE_Y','JOINT_LEFT_FOOT_Y','JOINT_RIGHT_FOOT_Y']] = \
        data[['JOINT_HEAD_Y','JOINT_NECK_Y','JOINT_LEFT_SHOULDER_Y',
        'JOINT_RIGHT_SHOULDER_Y','JOINT_LEFT_ELBOW_Y','JOINT_RIGHT_ELBOW_Y',
        'JOINT_LEFT_HAND_Y','JOINT_RIGHT_HAND_Y','JOINT_TORSO_Y',
        'JOINT_LEFT_HIP_Y','JOINT_RIGHT_HIP_Y','JOINT_LEFT_KNEE_Y',
        'JOINT_RIGHT_KNEE_Y','JOINT_LEFT_FOOT_Y','JOINT_RIGHT_FOOT_Y']].sub(data['JOINT_TORSO_Y'], axis=0)

    data[['JOINT_HEAD_Z','JOINT_NECK_Z','JOINT_LEFT_SHOULDER_Z',
        'JOINT_RIGHT_SHOULDER_Z','JOINT_LEFT_ELBOW_Z','JOINT_RIGHT_ELBOW_Z',
        'JOINT_LEFT_HAND_Z','JOINT_RIGHT_HAND_Z','JOINT_TORSO_Z',
        'JOINT_LEFT_HIP_Z','JOINT_RIGHT_HIP_Z','JOINT_LEFT_KNEE_Z',
        'JOINT_RIGHT_KNEE_Z','JOINT_LEFT_FOOT_Z','JOINT_RIGHT_FOOT_Z']] = \
        data[['JOINT_HEAD_Z','JOINT_NECK_Z','JOINT_LEFT_SHOULDER_Z',
        'JOINT_RIGHT_SHOULDER_Z','JOINT_LEFT_ELBOW_Z','JOINT_RIGHT_ELBOW_Z',
        'JOINT_LEFT_HAND_Z','JOINT_RIGHT_HAND_Z','JOINT_TORSO_Z',
        'JOINT_LEFT_HIP_Z','JOINT_RIGHT_HIP_Z','JOINT_LEFT_KNEE_Z',
        'JOINT_RIGHT_KNEE_Z','JOINT_LEFT_FOOT_Z','JOINT_RIGHT_FOOT_Z']].sub(data['JOINT_TORSO_Z'], axis=0)

    
    # datay = data[['JOINT_HEAD_Y','JOINT_NECK_Y','JOINT_TORSO_Y']].sub(data['JOINT_TORSO_Y'], axis=0)
    # dataz = data[['JOINT_HEAD_Z','JOINT_NECK_Z','JOINT_TORSO_Z']].sub(data['JOINT_TORSO_Z'], axis=0)
    # data = pd.concat([datax,datay,dataz], axis=1)
    #return data
    #print(data[[' JOINT_HEAD_X',' JOINT_NECK_X']])

normalize(data)
data.to_csv('./normalized_train.csv')
